#!/bin/bash

# Set the credential store to use the OSX KeyChain (should be Brew installed with git)
git config --global credential.helper osxkeychain

# Set your editor to MacVim by default
git config --global core.editor "mvim -f"
