#!/bin/bash

# Yawn, public credentials
git config --global user.name "Dustin Venegas"
git config --global user.email dustin.venegas@gmail.com

# For all repositories, ignore your messy leftover files
git config --global core.excludesfile ~/dotfiles/.gitignore_global

# Global editor to gvim. Test with: git config -e
git config --global core.editor vim

# Always use 3-way diffs
git config --global merge.conflictstyle diff3

# Setup vim merge and diff tools for those oh-so terminal moments
git config --global merge.tool vimdiff
git config --global mergetool.prompt false
git config --global diff.tool vimdiff

# Setup the alias section
git config --global include.path dotfiles/.gitconfig_global
