# Kitty terminal
cask "kitty"

# Enable the cask-fonts Homebrew repository.
tap "homebrew/cask-fonts"

# Installs the Hack font.
cask "font-hack"

# Install the Cascadia Code (with ligatures) font.
cask "font-cascadia-code"
