if (Get-Command -Name vim -CommandType Application -ErrorAction SilentlyContinue){
    $vimrcPath = "$HOME\.vimrc"
    $vimrcTemplate = @"
" Autogenerated by provision.ps1 on {{date}}
" Add dotfiles RTP
set runtimepath^={{vimrtp}}
" Source the dotfiles .vimrc
source {{vimrc}}
"@

    if (Test-Path $vimrcPath) {
        Write-Warning ".vimrc already exists at $vimrcPath"
    } else {
        Write-Host "Creating default .vimrc at $vimrcPath"
        $vimrcTemplate | ForEach-Object {
            $_  -replace '{{date}}',(Get-Date) `
                -replace '{{vimrtp}}',"$($PSScriptRoot.Replace('\','/'))/.vim" `
                -replace '{{vimrc}}',"$PSScriptRoot\.vimrc"
        } | Out-File -FilePath $vimrcPath -Encoding utf8
    }

    if ($false -eq (Test-Path "~/.vim/autoload/plug.vim")) {
        New-Item -Type Directory "~\vimfiles\autoload" -Force
        $uri = 'https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        (New-Object Net.WebClient).DownloadFile(
            $uri,
            $ExecutionContext.SessionState.Path.GetUnresolvedProviderPathFromPSPath(
                "~\vimfiles\autoload\plug.vim"
            )
        )
    }

    Write-Host "Updating vim plugins..."
    vim +PlugInstall +qall
} else {
    Write-Warning "vim not found"
}
