#!/usr/bin/env bash

# bash
HISTCONTROL=ignoreboth  # Ignore duplicate commands, or ones prefixed with a space
HISTSIZE=65535 # Keep lots of history. Default, 500

# golang
export GOPATH=$HOME/go
export GOROOT=/usr/local/opt/go/libexec
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin

# Set editor to nvim
export EDITOR=nvim

# Hook for desk activation
[ -n "$DESK_ENV" ] && source "$DESK_ENV" || true

# homebrew autocomplete
if type brew 2&>/dev/null; then
    for completion_file in $(brew --prefix)/etc/bash_completion.d/*; do
        source "$completion_file"
    done

    # git-prompt from git's built-in bash completion
    if [ -f "$(brew --prefix nvm)" ]; then
        export NVM_DIR="$HOME/.nvm"
        source "$(brew --prefix nvm)/nvm.sh"
    fi

    # node-version-manager
    if [ -f "$(brew --prefix nvm)" ]; then
        export NVM_DIR="$HOME/.nvm"
        source "$(brew --prefix nvm)/nvm.sh"
    fi
fi

# fzf - Fuzzy Finder for Bash
# NOTE: fzf contains an install script that sets up these functions and
# similar paths. The script may have updated functionallity since run on
# 2019/01/31 on a MacOS machine for bash.
# fzf - Setup pathing
# ---------
if [[ ! "$PATH" == */usr/local/opt/fzf/bin* ]]; then
    export PATH="$PATH:/usr/local/opt/fzf/bin"
fi

# fzf - Auto-completion
# ---------------
[[ $- == *i* ]] && source "/usr/local/opt/fzf/shell/completion.bash" 2> /dev/null

# fzf - Key bindings
# ------------
source "/usr/local/opt/fzf/shell/key-bindings.bash"

# .bashrc.local support, for local-only bash commands
if [ -f "$HOME/.bashrc.local" ]; then
    source $HOME/.bashrc.local
fi

