# bash-git-prompt provides a git prompt for BASH.
brew "bash-git-prompt"

# Enable the cask-fonts Homebrew repository.
tap "homebrew/cask-fonts"

# Installs the Hack font.
cask "font-hack"

# tree is useful for displaying file listings as a tree.
brew "tree"
