# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Install PowerShell
      run: dotnet tool install --global PowerShell
    - name: Install other dependencies
      run: sudo apt-get install zsh git -y
    - name: Bootstrap Script
      run: ./script/bootstrap.sh --verbose --force
    - name: Placeholder Git User/Pass
      run: git config --global 'user.name' 'placeholder' && git config --global 'user.email' 'placeholder@example.org'
    # - name : Install neovim
    #   run: sudo apt-get install neovim -y
    # - name: nvim update
    #   run: nvim +PlugInstall +qall
    # - name: vim update
    #   run: vim +PlugInstall +qall
    - name: Health Check
      run: ./script/check-dotfiles-health.sh
